name: Scala CI

on:
 push:
   branches:
     - main
     - dev
 pull_request:
   branches:
     - main
     - dev

jobs:
 scalatest_sbt:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Run tests
       run: sbt clean test coverage
     - name: Coverage Report
       run: sbt coverageReport
     - name: Coveralls GitHub Action
       uses: coverallsapp/github-action@v2.0.0